version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python:
      #Install our pytgon package befor building the docs
      install:
        -method: pip
        path: .

sphinx:
  fail_on_warning: true
